
import React, { useState, useEffect } from 'react';
import { getLiveBlogPosts } from '../services/geminiService';
import { BlogPost } from '../types';

interface BlogProps {
  isFullPage?: boolean;
}

const Blog: React.FC<BlogProps> = ({ isFullPage = false }) => {
  const [posts, setPosts] = useState<BlogPost[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedPost, setSelectedPost] = useState<BlogPost | null>(null);

  useEffect(() => {
    const fetchPosts = async () => {
      setLoading(true);
      const data = await getLiveBlogPosts();
      setPosts(data);
      setLoading(false);
    };
    fetchPosts();
  }, []);

  if (selectedPost) {
    return (
      <div className="animate-fade-in max-w-4xl mx-auto space-y-12 py-12">
        <button 
          onClick={() => setSelectedPost(null)}
          className="flex items-center gap-2 text-indigo-400 hover:text-indigo-300 transition-colors font-medium"
        >
          <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
          </svg>
          Back to Feed
        </button>
        
        <div className="space-y-6">
          <div className="flex items-center gap-4">
            <span className="px-3 py-1 bg-indigo-500/10 text-indigo-400 rounded-full text-xs font-bold uppercase tracking-widest">
              {selectedPost.category}
            </span>
            <span className="text-gray-500 font-mono text-xs">{selectedPost.date}</span>
          </div>
          <h1 className="text-5xl md:text-6xl font-extrabold leading-tight">{selectedPost.title}</h1>
          <p className="text-xl text-gray-400 leading-relaxed font-light">{selectedPost.summary}</p>
        </div>

        <div className="glass p-12 rounded-[2rem] border-indigo-500/20 text-center space-y-8">
          <div className="space-y-4">
            <h2 className="text-2xl font-bold">Ready for the full deep dive?</h2>
            <p className="text-gray-400">This article was curated from a verified technical source. Read the full technical documentation or news report below.</p>
          </div>
          <a 
            href={selectedPost.url} 
            target="_blank" 
            rel="noopener noreferrer"
            className="inline-block px-10 py-5 bg-indigo-600 text-white font-bold rounded-2xl hover:bg-indigo-500 transition-all hover:scale-105 shadow-xl shadow-indigo-600/20"
          >
            Read Original Article
          </a>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-12">
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-6">
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20">
            <span className="w-2 h-2 bg-indigo-500 rounded-full animate-pulse" />
            <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest">Live Pulse</span>
          </div>
          <h2 className="text-4xl md:text-5xl font-bold">Engineering Chronicles</h2>
        </div>
        <p className="text-gray-400 max-w-sm font-light text-sm">
          Dynamic technical insights generated by Gemini 3 Flash with real-time Google Search grounding.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {loading ? (
          Array.from({ length: 3 }).map((_, i) => (
            <div key={i} className="glass p-6 rounded-3xl h-64 animate-pulse space-y-4">
              <div className="h-4 w-20 bg-white/10 rounded" />
              <div className="h-8 w-full bg-white/10 rounded" />
              <div className="h-20 w-full bg-white/10 rounded" />
            </div>
          ))
        ) : (
          posts.map((post, idx) => (
            <div 
              key={idx} 
              onClick={() => setSelectedPost(post)}
              className="group glass p-8 rounded-3xl flex flex-col justify-between hover:border-indigo-500/40 transition-all hover:scale-[1.02] cursor-pointer relative overflow-hidden"
            >
              <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-100 transition-opacity">
                <svg className="w-6 h-6 rotate-45" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 10l7-7m0 0l7 7m-7-7v18" />
                </svg>
              </div>

              <div className="space-y-4">
                <div className="flex justify-between items-center">
                  <span className="text-[10px] font-bold text-indigo-400 uppercase tracking-widest px-2 py-1 bg-indigo-500/10 rounded">
                    {post.category}
                  </span>
                  <span className="text-[10px] text-gray-500 font-mono">{post.date}</span>
                </div>
                <h3 className="text-xl font-bold group-hover:text-indigo-400 transition-colors">
                  {post.title}
                </h3>
                <p className="text-sm text-gray-400 line-clamp-3 font-light leading-relaxed">
                  {post.summary}
                </p>
              </div>

              <div className="mt-8 pt-4 border-t border-white/5 flex items-center justify-between">
                <span className="text-xs font-semibold text-white/50 group-hover:text-white transition-colors">Read Full Post</span>
                <div className="flex items-center gap-1">
                  <div className="w-1 h-1 bg-green-500 rounded-full" />
                  <span className="text-[10px] text-gray-500">Source: {new URL(post.url).hostname.replace('www.', '')}</span>
                </div>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default Blog;
